hr_data<-read.csv("C:/Users/HP/Desktop/Imarticus/EMPLOYEE DATASET/HR dataset.csv")
View(hr_data)
hr_data1 <- hr_data[,-c(9,10)]
hr_data1$role_code = as.factor (hr_data1$role_code)
hr_data1$salary.code = as.factor (hr_data1$salary.code)
View(hr_data1)
summary(hr_data1)
hist(hr_data1$promotion_last_5years)
hist(hr_data1$role_code)
View(hr_data1)
summary(hr_data1)
boxplot(hr_data1$satisfaction_level ~ hr_data1$left, main = "Boxplot for satisfaction_level") 
boxplot(hr_data1$average_montly_hours ~ hr_data1$left, main = "Boxplot for Avg monthly hours")
boxplot(hr_data1$time_spend_company ~ hr_data1$left , main = "Boxplot for Time Spend With Company")
mosaicplot(hr_data1$left ~ hr_data1$salary.code, color = 'skyblue')
mosaicplot(hr_data1$left ~ hr_data1$promotion_last_5years, color = 'skyblue')
install.packages("corrplot")
library(corrplot)
cor(hr_data1[,1:6])
corrplot(cor(hr_data1[,1:8]),method = "circle")
set.seed(1234)
install.packages("carrot")
library(caret)
splitIndex <- createDataPartition(hr_data1$left, p = .70, list = FALSE, times = 1)
trainSplit <-hr_data1[splitIndex,]
testSplit <- hr_data1[-splitIndex,]
print(table(trainSplit$left))
print(table(testSplit$left))
prop.table(table(trainSplit$left))
prop.table(table(testSplit$left))
install.packages("rpart")
library(rpart)
library(rpart.plot)
install.packages("rpart.plot")
library(rpart.plot)
fit = rpart (left ~ ., data = trainSplit, method = "class")
rpart.plot (fit,cex = .7)
plotcp(fit)
fit = rpart (left ~ ., data = trainSplit, method = "class", control = rpart.control (cp = 0.023))
rpart.plot(fit)
fit = rpart (left ~ ., data = trainSplit, method = "class", control = rpart.control (minsplit = 500, cp = 0.023))
rpart.plot(fit)
predtr <- predict (fit, trainSplit, type = "class" )
library(caret)
confusionMatrix(as.factor(predtr), as.factor(trainSplit$left))
predtr <- predict (fit, trainSplit, type = "class" )
predtest <- predict (fit, testSplit, type = "class")                
confusionMatrix(as.factor(predtest), as.factor(testSplit$left))
install.packages("randomForest", dependencied = T)
library(randomForest)
modelrf <- randomForest(as.factor (left) ~ . , data = trainSplit, do.trace=T)
modelrf
predrf_tr <- predict (modelrf, trainSplit)
predrf_test <- predict(modelrf, testSplit)
library(caret)
confusionMatrix(as.factor(predrf_tr),as.factor(trainSplit$left))
confusionMatrix(as.factor(predrf_test),as.factor(testSplit$left))
importance(modelrf)
varImpPlot(modelrf)
